server:
  port: 8081
spring:
  application:
    name: app-flyway
  datasource:
    url: jdbc:postgresql://localhost:5432/app-flyway
    driverClassName: org.postgresql.Driver
    username: postgres
    password: example
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    show-sql: true

#flyway:
#  user: postgres
#  password: example
#  schemas: public
#  url: jdbc:postgresql://localhost:5432/app-flyway
#  locations: classpath:db/migration