eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 15

  server:
     enable-self-preservation: false