# Server port
server.port=8081

# Application name
spring.application.name=ec2-s3-iam-role

# --- Custom AWS Configuration ---
# Prefix your custom properties to avoid collisions.
# The `AwsConfig` bean will read these explicitly.
aws.s3.region=ap-southeast-2
# For local development, you might store credentials here.
# For production, it's recommended to use IAM roles or environment variables.
aws.s3.credentials.access-key=YOUR_ACCESS_KEY
aws.s3.credentials.secret-key=YOUR_SECRET_KEY
aws.s3.bucket=testing-s3-ec2-iam-role
